version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9091"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    ports:
      - "3000:3001"
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
    # Ensure network persists across restarts
    name: monitoring_network
