server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: update_checker
    static_configs:
      - targets:
          - localhost
        labels:
          job: update_checker
          __path__: /var/log/update-checker.log
    pipeline_stages:
      - regex:
          expression: '^(?:\[(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (?:update-checker|update-executor): (?P<level>\w+) - (?P<message>.*)|(?P<docker_message>Docker compose:.*)|\[(?P<timestamp2>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (?:update-executor): (?P<level2>\w+) - (?P<message2>.*))$'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
      - timestamp:
          source: timestamp2
          format: '2006-01-02 15:04:05'
      - output:
          source: message
          fallback_to: docker_message
          fallback_to: message2
